<?php
/**
 * HelloResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AutomationTestWithSubmodules
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Test Automation (No submodules)
 *
 * SDKs (no submodules) to test automation workflows.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace AutomationTestWithSubmodules\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HelloResponseTest Class Doc Comment
 *
 * @category    Class
 * @description HelloResponse
 * @package     AutomationTestWithSubmodules
 */
class HelloResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HelloResponse"
     */
    public function testHelloResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
