<?php
/**
 * GreetingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  AutomationTestWithSubmodules
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Test Automation (No submodules)
 *
 * SDKs (no submodules) to test automation workflows.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace AutomationTestWithSubmodules\Test\Api;

use \AutomationTestWithSubmodules\Configuration;
use \AutomationTestWithSubmodules\ApiException;
use \AutomationTestWithSubmodules\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class GreetingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for hello
     *
     * Get a simple greeting!!!.
     *
     */
    public function testHello()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
